# Get the latest versions of Valgrind/GCC by using tumbleweed
FROM opensuse/tumbleweed
RUN zypper in -y gcc gcc-c++ valgrind bmake git python3 python3-pexpect python3-pip cmake ninja
RUN pip install junitparser

